Add missing include to <mutex>
In file included from $SRC_DIR/ros-humble-slam-toolbox/src/work/lib/karto_sdk/src/Karto.cpp:27:
$SRC_DIR/ros-humble-slam-toolbox/src/work/lib/karto_sdk/include/karto_sdk/Karto.h: In member function 'const karto::Pose2& karto::LocalizedRangeScan::GetBarycenterPose() const':
$SRC_DIR/ros-humble-slam-toolbox/src/work/lib/karto_sdk/include/karto_sdk/Karto.h:5503:12: error: 'unique_lock' is not a member of 'std'
 5503 |       std::unique_lock<std::shared_mutex> uniqueLock(m_Lock);
      |            ^~~~~~~~~~~